Repository SOPT-all/36-COLLABORATION-SERVER-TODO-MATE, pull requests merged in 2025-05, with the labels that each got.

#4 [feat] 엔티티 설정 및 유저 조회로직 구현
  src/main/java/com/sopt/todomate/domain/maintask/domain/entity/MainTask.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/entity/RoutineCycle.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/repository/MainTaskRepository.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/entity/SubTask.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/repository/SubTaskRepository.java
  src/main/java/com/sopt/todomate/domain/user/domain/entity/User.java
  src/main/java/com/sopt/todomate/domain/user/domain/repository/UserRepository.java
  src/main/java/com/sopt/todomate/domain/user/domain/service/UserGetService.java
  src/main/java/com/sopt/todomate/domain/user/exception/UserNotFoundException.java
  src/test/java/com/sopt/todomate/domain/user/domain/service/UserGetServiceTest.java
Labels: feat

#6 [feat] 태스크 생성로직 구현
  build.gradle
  src/main/java/com/sopt/todomate/domain/maintask/application/dto/MainTaskCommand.java
  src/main/java/com/sopt/todomate/domain/maintask/application/dto/SubTaskCommand.java
  src/main/java/com/sopt/todomate/domain/maintask/application/usecase/MainTaskManageUsecase.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/entity/MainTask.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/entity/RoutineCycle.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/entity/RoutineType.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/repository/MainTaskRepository.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/service/MainTaskSaveService.java
  src/main/java/com/sopt/todomate/domain/maintask/exception/EmptyRoutineDateException.java
  src/main/java/com/sopt/todomate/domain/maintask/exception/InvalidRountineTypeException.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/MainTaskController.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/MainTaskCreateRequest.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/MainTaskCreateResponse.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/SubTaskDto.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/SubTaskResponse.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/entity/SubTask.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/repository/SubTaskRepository.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/service/SubTaskSaveService.java
  src/main/java/com/sopt/todomate/domain/user/domain/entity/User.java
  src/main/java/com/sopt/todomate/global/common/entity/BaseEntity.java
  src/main/java/com/sopt/todomate/global/common/exception/ExceptionResponse.java
  src/main/java/com/sopt/todomate/global/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sopt/todomate/global/common/exception/constant/ExceptionCode.java
  src/main/java/com/sopt/todomate/global/config/EnableJpaAuditingConfig.java
  src/main/java/com/sopt/todomate/global/config/SwaggerConfig.java
  src/test/java/com/sopt/todomate/domain/maintask/application/usecase/MainTaskManageUsecaseTest.java
  src/test/java/com/sopt/todomate/domain/user/domain/service/UserGetServiceTest.java
Labels: feat

#9 refactor: 카테고리를 enum타입으로 관리되도록 리팩토링
  src/main/java/com/sopt/todomate/domain/maintask/application/dto/MainTaskCommand.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/entity/CategoryType.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/entity/MainTask.java
  src/main/java/com/sopt/todomate/domain/maintask/exception/InvalidCategoryTypeException.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/MainTaskCreateRequest.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/MainTaskCreateResponse.java
  src/main/java/com/sopt/todomate/global/common/exception/constant/ExceptionCode.java
  src/test/java/com/sopt/todomate/domain/maintask/application/usecase/MainTaskManageUsecaseTest.java
Labels: refactor

#10 [feat] 태스크 수정 API 구현
  src/main/java/com/sopt/todomate/domain/maintask/application/dto/MainTaskCommand.java
  src/main/java/com/sopt/todomate/domain/maintask/application/dto/MainTaskUpdateCommand.java
  src/main/java/com/sopt/todomate/domain/maintask/application/dto/SubTaskUpdateCommand.java
  src/main/java/com/sopt/todomate/domain/maintask/application/usecase/MainTaskManageUsecase.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/entity/CategoryType.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/entity/Importance.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/entity/MainTask.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/repository/MainTaskRepository.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/service/MainTaskGetService.java
  src/main/java/com/sopt/todomate/domain/maintask/exception/AccessDeniedException.java
  src/main/java/com/sopt/todomate/domain/maintask/exception/InvalidImportanceException.java
  src/main/java/com/sopt/todomate/domain/maintask/exception/MainTaskNotFoundException.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/MainTaskController.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/MainTaskCreateRequest.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/MainTaskCreateResponse.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/MainTaskUpdateRequest.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/entity/SubTask.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/repository/SubTaskRepository.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/service/SubTaskDeleteService.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/service/SubTaskGetService.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/service/SubTaskUpdateService.java
  src/main/java/com/sopt/todomate/domain/subtask/exception/MaxSubTaskException.java
  src/main/java/com/sopt/todomate/domain/subtask/exception/SubTaskNotFoundException.java
  src/main/java/com/sopt/todomate/domain/subtask/exception/SubTaskNotIncludeException.java
  src/main/java/com/sopt/todomate/global/common/exception/constant/ExceptionCode.java
  src/test/java/com/sopt/todomate/domain/maintask/application/usecase/MainTaskManageUsecaseTest.java
Labels: feat, refactor

#15 [refactor] 리뷰 반영 및 메인 태스크 및 서브 태스크 최신순 정렬
  src/main/java/com/sopt/todomate/domain/maintask/application/usecase/MainTaskQueryUsecase.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/repository/MainTaskRepository.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/service/MainTaskGetService.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/repository/SubTaskRepository.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/service/SubTaskGetService.java
Labels: refactor

#16 [fix] 서브태스크, 메인태스크 생성로직 분할
  src/main/java/com/sopt/todomate/domain/maintask/application/dto/MainTaskCommand.java
  src/main/java/com/sopt/todomate/domain/maintask/application/dto/SubTaskCommand.java
  src/main/java/com/sopt/todomate/domain/maintask/application/dto/SubTaskUpdateCommand.java
  src/main/java/com/sopt/todomate/domain/maintask/application/usecase/MainTaskManageUsecase.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/entity/MainTask.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/repository/MainTaskRepository.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/service/MainTaskGetService.java
  src/main/java/com/sopt/todomate/domain/maintask/exception/MaxMainTaskException.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/MainTaskController.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/MainTaskQueryController.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/MainTaskCreateRequest.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/MainTaskCreateResponse.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/SubTaskDto.java
  src/main/java/com/sopt/todomate/domain/subtask/application/SubTaskManageUsecase.java
  src/main/java/com/sopt/todomate/domain/subtask/application/dto/SubTaskCreateCommand.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/entity/SubTask.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/service/SubTaskSaveService.java
  src/main/java/com/sopt/todomate/domain/subtask/presentation/SubTaskController.java
  src/main/java/com/sopt/todomate/domain/subtask/presentation/dto/SubTaskCreateRequest.java
  src/main/java/com/sopt/todomate/domain/subtask/presentation/dto/SubTaskCreateResponse.java
  src/main/java/com/sopt/todomate/global/common/exception/constant/ExceptionCode.java
  src/test/java/com/sopt/todomate/domain/maintask/application/usecase/MainTaskManageUsecaseTest.java
  src/test/java/com/sopt/todomate/domain/subtask/application/SubTaskManageUsecaseTest.java
Labels: bug

#19 [feat] 서브태스크 완료여부 변경 API 구현
  src/main/java/com/sopt/todomate/domain/maintask/application/usecase/MainTaskManageUsecase.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/MainTaskController.java
  src/main/java/com/sopt/todomate/domain/subtask/application/SubTaskManageUsecase.java
  src/main/java/com/sopt/todomate/domain/subtask/application/dto/SubTaskCompletedCommand.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/entity/SubTask.java
  src/main/java/com/sopt/todomate/domain/subtask/presentation/SubTaskController.java
  src/main/java/com/sopt/todomate/domain/subtask/presentation/dto/SubTaskCompletedRequest.java
  src/main/java/com/sopt/todomate/global/common/dto/ResponseDto.java
  src/main/java/com/sopt/todomate/global/common/dto/constant/SuccessCode.java
  src/test/java/com/sopt/todomate/domain/subtask/application/SubTaskManageUsecaseTest.java
Labels: feat, refactor

#21 [feat] 삭제 기능 구현
  src/main/java/com/sopt/todomate/domain/maintask/application/usecase/MainTaskManageUsecase.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/repository/MainTaskRepository.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/service/MainTaskDeleteService.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/service/MainTaskGetService.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/MainTaskController.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/repository/SubTaskRepository.java
  src/main/java/com/sopt/todomate/domain/subtask/domain/service/SubTaskDeleteService.java
  src/main/java/com/sopt/todomate/domain/subtask/presentation/SubTaskController.java
Labels: feat, refactor

#22 [feat] 메인태스크 완료여부 변경 API 구현
  src/main/java/com/sopt/todomate/domain/maintask/application/dto/MainTaskCompletedCommand.java
  src/main/java/com/sopt/todomate/domain/maintask/application/usecase/MainTaskManageUsecase.java
  src/main/java/com/sopt/todomate/domain/maintask/domain/entity/MainTask.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/MainTaskController.java
  src/main/java/com/sopt/todomate/domain/maintask/presentation/dto/MainTaskCompletedRequest.java
Labels: feat
